### ISSUE TITLE
string is vulnerable (<=99.999.99999). Patched versions: <0.0.0

### ISSUE THREAD

**Issue by xxlbug** [hsz/idea-nodesecurity#7]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet

### Description

In the package.json from the [swagger codegen tool for a nodejs-server](https://editor.swagger.io) i get a Error with the newest version of node security (0.4.0):
```
string is vulnerable (<=99.999.99999). Patched versions: <0.0.0
```

I get the error only for the "swagger-tools: "0.10.3" entry, here the full package.json:

```
{
  "name": "api-storage",
  "version": "0.1.0",
  "description": "Store all your api in one place and let other services consume them",
  "main": "index.js",
  "keywords": [
    "swagger"
  ],
  "license": "Unlicense",
  "private": true,
  "dependencies": {
    "js-yaml": "^3.3.0",
    "swagger-tools": "0.10.3"
  }
}
```

### Versions

**Plugin:** 

```
0.4.0
```

**IDE:** 

```
IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 29, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3
```

**Comment by hsz** [comment]
So it looks like this package has not been fixed yet and it's vulnerable.
In the next releases I'll implement some mechanism that will allow to _accept the risk_ and turn off this information - as suggested in #3

**Comment by xxlbug** [comment]
I don't think so, except you use another source than nodesecurity.io. There is no open advisory for "swagger-tools" right now: https://nodesecurity.io/advisories?search=swagger-tools

**Comment by hsz** [comment]
Yeah, but `swagger-tools` has a dependency to `string` package.

https://nodesecurity.io/advisories?search=String

**Comment by xxlbug** [comment]
I read "string", i thought "string" as in text and didn't think twice about that there could be a node package called "string".

Thank you for your time, issue is done 👍
